pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    
    stage('Checkout') {
      agent any
            steps {
                // Check out the code from your version control system (e.g., Git)
                git 'https://github.com/Sekharbabu12/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Build') {
            steps {
                // Build your Java project using Maven
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                // Run tests if applicable
                sh 'mvn test'
            }
        }

    
    

    post {
        success {
            // Actions to perform when the pipeline succeeds
            echo 'HelloWorld Java code built and tested successfully!'
        }

        failure {
            // Actions to perform when the pipeline fails
            echo 'Pipeline failed. Please check the build logs.'
        }
    }




     
        
  }
}
